### PR TITLE
Re-merge Goal abortion

### PR DESCRIPTION
**Pull request by dorkamotorka**
Beside the thing that I deleted (I re-added it) I also removed parameter in rotate function, because there seem to be un-used.

### CODE REVIEW

**Comment by dorkamotorka** [comment]
The goal abortion methods were still there after the successful merge(They were only deleted on kinetic-devel branch)

**Comment by rohbotics** [comment]
This doesn't look like it re-adds the feature?

**Comment by tp4348** [comment]
There is just some confusion going on here, because I messed up something. If you look into the source code of the branch from which I am merging, the changes are applied.

**Comment by dorkamotorka** [comment]
I dont know how to explain it, but the source code of my branch goal-abort looks fine.

**Pull request closed without merging**
