### PR TITLE
Initial support for queuing action goals.

### PR DESCRIPTION
**Pull request by rohbotics**
This should allow us to implement the smooth turning later.

Still needs unit testing.

Related to #53

### CODE REVIEW

**Comment by MoffKalast** [comment]
Looks like a solid starting point from what I can tell, though I'm not entirely sure how the client can track the two goals. Since it should be able to cancel or preempt either.

**Comment by rohbotics** [comment]
I think this is enough to unblock us with smooth turning. For breadcrumb, I am not sure we need the ability to preempt at all initially.

If we were to need it, we would need to get clients to use something other than simple_action_client that can handle multiple goals in flight.

**Comment by MoffKalast** [comment]
Well not necessarily, what I did in my first attempt (while I trying to implement a custom length queue) was add a separate publisher for the goals that the client can then independently subscribe to. After all the client should merely need the correct IDs to change goals in the queue as needed.

But yeah I agree, we can probably make it work with just this for now.

**Comment by rohbotics** [comment]
@MoffKalast I made a separate issue regarding unit tests, I am merging this PR now so that we can keep making progress.

**Pull request merged**
